<el-date-picker 
    size='medium' 
    class='w-100' 
    clearable
    v-model='{{"filter.$index"}}' 
    @change='makeNewRoute' 
    type='date'
    :format='dd/MM/yyyy'
    value-format='yyyy-MM-dd'
    placeholder='{{$placeholder}}'>
</el-date-picker>