<v-input class='mb-3'  
    :disabled='{{$disabled}}'                                                                  
    label='{{$label}}'                                                                   
    prepend='{{$prepend}}'                                                               
    append='{{$append}}'                                                               
    append='{{$append}}' 
    :mask='{{$mask}}'                                                              
    description='{{$description}}'                                                              
    type='{{$type}}'                                                                     
    v-model='{{"form.$field"}}'                                                            
    placeholder='{{$placeholder}}'   
    v-show='{{$visible}}'                                                    
    :errors='{{"errors.$field ? errors.$field : false"}}'                
/>